### PR TITLE
Fix building with Qt 5.14

### PR DESCRIPTION
**Pull request by yan12125**

### CODE REVIEW

**Comment by tsujan** [comment]
@yan12125 
Do you know how `QFile` was included before 5.14?

**Comment by arthurzam** [comment]
For me, it started to build fail after 9e619cf45a6f7431c3f3a0ea24e11acb40c34cb2 commit.

**Comment by yan12125** [comment]
tsujan <notifications@github.com> 於 2019年12月15日 週日 下午4:51寫道：
>
> @yan12125
> Do you know how QFile was included before 5.14?
>

Here is what I found from `g++ -E`: lxqtpower/lxqtpower.h ->
/usr/include/qt/QtGui/QList -> /usr/include/qt/QtGui/qevent.h ->
/usr/include/qt/QtCore/qfile.h

Paths for the other two similar PRs in LXQt:
* lxqt-conf, the path is lxqt-config-input/touchpaddevice.h ->
/usr/include/qt/QtGui/QList -> /usr/include/qt/QtGui/qevent.h ->
/usr/include/qt/QtCore/qurl.h
* lxqt-globalkeys: daemon/core.h -> /usr/include/qt/QtGui/QList ->
/usr/include/qt/QtGui/qevent.h -> /usr/include/qt/QtCore/qfile.h

This commit seems related:
https://github.com/qt/qtbase/commit/bfed3cf41947baec29e88585cfdebf8ebae6ad39#diff-d8dfcd1a005d75b361b69d9ec607b2e2

**Comment by Chiitoo** [comment]
I haven't been able to spot the exact commit that introduced the change, but if I remember right, https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.14&id=aef07a43 is the last 'good' commit.  Maybe +/- one commit... been a while now.  :]

I asked Qt directly via IRC, too, but didn't get answers yet.  Will try again this week.

The merge [1] around the time of said commit does not make regression testing easier to me at least.

1. https://code.qt.io/cgit/qt/qtbase.git/log/?h=5.14&qt=range&q=bf131e8d...8693c07a

**Comment by yan12125** [comment]
Gonna merge. I will post a backport patch for liblxqt 0.14.1 soon.

**Comment by yan12125** [comment]
> I will post a backport patch for liblxqt 0.14.1 soon.

Here it is: https://git.archlinux.org/svntogit/community.git/tree/liblxqt/trunk/qt5.14.diff?id=45f2702994d66227b4f2021ffbd7d2ad8f0da666

**Pull request merged**
